Big changes

diff --git a/.local/bin/mailsync b/.local/bin/mailsync
--- a/.local/bin/mailsync
+++ b/.local/bin/mailsync
@@ -1,6 +1,59 @@
 #!/bin/sh
 
-pgrep -u "$USER" >/dev/null || { echo "$USER not logged in; sync will not run."; exit ;}
+# Sync mail and give notification if there is new mail.
+ping -q -c 1 1.1.1.1 > /dev/null || exit
 
-mbsync -a
-notmuch new
+# Run only if user logged in (prevent cron errors)
+pgrep -u "${USER:=$LOGNAME}" >/dev/null || { echo "$USER not logged in; sync will not run."; exit ;}
+# Run only if not already running in other instance
+pgrep -x mbsync >/dev/null && { echo "mbsync is already running." ; exit ;}
+
+# Required to display notifications if run as a cronjob:
+export XDG_CACHE_HOME="$HOME"/.cache
+export XDG_CONFIG_HOME="$HOME"/.config
+export XDG_DATA_HOME="$HOME"/.local/share
+export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
+export DISPLAY=:0
+export NOTMUCH_CONFIG="$XDG_CONFIG_HOME"/notmuch/notmuchrc
+export NMBGIT="$XDG_DATA_HOME"/notmuch/nmbug
+export GNUPGHOME="$XDG_DATA_HOME"/gnupg
+
+# Check account for new mail. Notify if there is new content.
+syncandnotify() {
+	acc="$(echo "$account" | sed "s/.*\///")"
+	mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc "$acc"
+    new=$(find "$HOME/.local/share/mail/$acc/INBOX/new/" -type f -newer "$HOME/.config/mutt/.mailsynclastrun" 2> /dev/null)
+    newcount=$(echo "$new" | sed '/^\s*$/d' | wc -l)
+    if [ "$newcount" -gt "0" ]; then
+        for file in $new; do
+            # Extract subject and sender from mail.
+            from=$(awk '/^From: / && ++n ==1,/^\<.*\>:/' "$file" | perl -CS -MEncode -ne 'print decode("MIME-Header", $_)' | awk '{ $1=""; if (NF>=3)$NF=""; print $0 }' | sed 's/^[[:blank:]]*[\"'\''\<]*//;s/[\"'\''\>]*[[:blank:]]*$//')
+            subject=$(awk '/^Subject: / && ++n == 1,/^\<.*\>: / && ++i == 2' "$file" | head -n-1 | perl -CS -MEncode -ne 'print decode("MIME-Header", $_)' | sed 's/^Subject: //' | sed 's/^{[[:blank:]]*[\"'\''\<]*//;s/[\"'\''\>]*[[:blank:]]*$//' | tr -d '\n')
+            notify-send "📧$from:" "$subject" &
+        done
+    fi
+}
+
+accounts="$(awk '/^Channel/ {print $2}' "$XDG_CONFIG_HOME"/isync/mbsyncrc)"
+
+echo " 🔃" > /tmp/imapsyncicon_"$USER"
+( pkill -RTMIN+12 dwmblocks >/dev/null 2>&1 ) 2>/dev/null
+
+# Parallelize multiple accounts
+for account in $accounts
+do
+    syncandnotify &
+done
+
+wait
+rm -f /tmp/imapsyncicon_"$USER"
+( pkill -RTMIN+12 dwmblocks >/dev/null 2>&1 ) 2>/dev/null
+
+notmuch new 2>/dev/null
+notmuch tag +college from:"/University/" or from:"/College/" or "university" or "college" and folder:"xyz/INBOX"
+for list in $(cat ~/.local/share/mailinglists); do
+	notmuch tag +list to:"$list" and folder:"xyz/INBOX"
+done
+
+#Create a touch file that indicates the time of the last run of mailsync
+touch "$XDG_CONFIG_HOME/mutt/.mailsynclastrun"
